### ISSUE TITLE
Dart pub get fails to install on Dart < 3.6

### ISSUE THREAD

**Issue by bivens-dev** [shamblett/cbor#69]
Example of running dart pub get with Dart 3.5.4:

```bash
[cbor] dart pub get --no-example
Resolving dependencies...
The current Dart SDK version is 3.5.4.

Because cbor depends on lints >=5.1.0 which requires SDK version >=3.6.0-0 <4.0.0, version solving failed.


You can try one of the following suggestions to make the pubspec resolve:
* Try using the Dart SDK version: 3.6.1. See https://dart.dev/get-dart.
* Consider downgrading your constraint on lints: dart pub add dev:lints:^5.0.0
exit code 1
```

Relevant version constraints from `pubspec.yaml`:
```yaml
environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: '^5.1.1'
```
